### ISSUE TITLE
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)

### ISSUE THREAD

**Issue by ZongzhiWu** [AnantharamanLab/PropagAtE#10]
**Error**
Traceback (most recent call last):
  File "/home/wuzongzhi2022phd/miniconda/envs/propagate/bin/Propagate", line 273, in <module>
    total = modules.extract_coverage(bamfile, read_id, lengths, mask, outfile, prophage_dict, effect, ratio_cutoff, prophage_dict_frags, prophage_lengths, min_breadth, min_cov, args.clean, spaces)
  File "/home/wuzongzhi2022phd/miniconda/envs/propagate/bin/modules.py", line 340, in extract_coverage
    written, total = write_coverages(outfile, prophage_covs, prev, avg, med, sd, eff_host, effect, ratio_cutoff, written, total, min_breadth, min_cov, spaces)
  File "/home/wuzongzhi2022phd/miniconda/envs/propagate/bin/modules.py", line 447, in write_coverages
    d = cohenD(phage_mean, phage_sd, avg, sd)
  File "/home/wuzongzhi2022phd/miniconda/envs/propagate/lib/python3.6/site-packages/numba/core/dispatcher.py", line 418, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/home/wuzongzhi2022phd/miniconda/envs/propagate/lib/python3.6/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/home/wuzongzhi2022phd/miniconda/envs/propagate/lib/python3.6/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
'try' block not supported until python3.7 or later

File "../../../miniconda/envs/propagate/bin/modules.py", line 412:
def cohenD(phage_mean, phage_sd, host_mean, host_sd):
    <source elided>
    """
    try:
    ^

**Log**
Command:    /home/wuzongzhi2022phd/miniconda/envs/propagate/bin/Propagate -f /home/wuzongzhi2022phd/03HSH/19PropagAtE/scanfold.fasta -r /home/wuzongzhi2022phd/03HSH/01cleandata/BC_SD_1.fastq /home/wuzongzhi2022phd/03HSH/01cleandata/BC_SD_2.fastq -v /home/wuzongzhi2022phd/03HSH/19PropagAtE/manual_prophage_coordinates.tsv -o /home/wuzongzhi2022phd/03HSH/19PropagAtE/PropagAtE_output/BC_SD --clean -t 48

Date:       2023-05-11
Time:       20:30:05
Program:    PropagAtE v1.1.0

Time (min) Log
0.0         Reads input identified, using 48 threads to run Bowtie2.
16.1         Checking if BAM file needs to be sorted
16.1         Generating a list of all prophage regions
16.1         Number of prophage regions identified: 1037
16.1         Number of unique host regions identified: 1034
16.1         Extracting coverage and performing statistical analyses

**Comment by ZongzhiWu** [comment]
Fixed

**Comment by alvinn011** [comment]
how did you fix it??
